@startuml 数据质量_流程图

actor 用户

用户 -> victini : 1.选择数据源

用户 -> victini : 2.根据数据应用场景配置数据质量规则

victini -> 规则引擎 : 3.保存数据质量规则

victini -> 运行引擎 : 4.提交启动数据质量监控任务

运行引擎 -> 运行引擎 : 5.数据源数据逐条校验

alt 告警质量规则
运行引擎 -> 异步队列 : 6.数据质量告警报告
else skip质量规则 | 阻断质量规则
运行引擎 -> 异步队列 : 6.数据质量报告发送
运行引擎 -> 运行引擎 : 6.skip或阻断 
end

质量处理引擎 --> 异步队列 : 7.逐条拉取数据质量报告

alt 告警报告
质量处理引擎 -> 钉钉 : 8.数据质量告警
else 阻断报告且需外部阻断
质量处理引擎 -> 运行引擎 : 8.阻断任务
end

@enduml