@startuml 数据质量组件图-内嵌模式

interface 配置数据质量规则 as configRule

package "数据质量中心-规则引擎" {
    [规则查询组件]
    [规则存储组件]
}

package "计算任务逻辑"{
    [计算任务逻辑开发(DAG)]
}

package "运行引擎" {
    frame "Runtime"{
        [数据质量逻辑]
        [任务逻辑]
    }
}

node "异步队列"

package "质量监控组件" {
    [质量事件监控组件]
}

configRule --> 规则存储组件
计算任务逻辑 --> Runtime : 任务逻辑
规则查询组件 --> Runtime : 内嵌监控逻辑
数据质量逻辑 ..> 异步队列 : 不符规则数据消息
质量事件监控组件 ..> 异步队列 : consume

@enduml